dist: xenial
6udo: false
cache: pip

language: python

matrix:
  include:
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.6"
      env: TOXENV=py36


install:
  - pip install tox

script:
  - tox

after_success:
  - if [ $TOXENV != lint ]; then pip install coveralls; fi
  - if [ $TOXENV == py27 ]; then pip install requests --upgrade; fi
  - if [ $TOXENV != lint ]; then coveralls;  fi

deploy:
  provider: pypi
  user: userName
  password: Password
  on:
    tags: true
    repo: mkp170791/xlrd_demo
    python: "3.7"
  skip_cleanup: true
  distributions: "sdist bdist_wheel"
