dist: xenial
6udo: false
cache: pip

language: python

matrix:
  include:
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.6"
      env: TOXENV=py36


install:
  - pip install tox

script:
  - tox

after_success:
  - if [ $TOXENV != lint ]; then pip install coveralls; fi
  - if [ $TOXENV == py27 ]; then pip install requests --upgrade; fi 
  - if [ $TOXENV != lint ]; then coveralls;  fi
before_deploy:
  - git config --global user.name "mpmkp2020"
  - git config --global user.email "madhukarhbti@gmail.com"
  - git config --global --list
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - python setup.py bdist_wheel
  - pwd
  - ls
  
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: JOAbnuEAtAOymiCMyUtydbrkhtM3PeGOZyRmGH2o4zhrH4fwBh46pjnoJiKpx4J5FdZ97tbqtvYgM6dSyTaWFllAw2lv6BuvdLOxW6nJVViX9urOHCbjgdWsQkoxFLcakhbmqSpzw1Dev/N9aqtIsui6z9vWV2OMwReSpFnHotnYIPrZBKcJFaeZIpo9+X5jFU3MokrZoZITD07HmsftN+m9LIsdSlKY0778ueh6LgxOX78juUSMosBr718XmUAuXJwCvH16T+dKkAvwprBUCOnVVXBFwtFajxbVq6rEgtsEVgZgPHgKgMR8KF/1c9Oj48EOOnmJFy+GBdRPyokJKPjNW7LpIAwH4DsJFT2HLybzI9jsandGPG8/RCMa1nSSoRoz1lpORnOeZ1TxLnAvxuAni73ySrx3f918jyI0Ns2pUDM0iID/5GHHiLRBmh0QH4cxRFY4PrjAoDP/ndeb1xhMJ8Vsti+GkPub58aQtL/2McCBZRyLp05E0TnErtR5Y1WVyiySTc6rzy4+PdvkmX/HDtElgcWCvk5eusgFVAryEIeqJuwBCxNR1HBV5FtHAp2ehQzdZYj3Vcy9Bz6ZMUd7ermNLLQVihLS1fYwW/xbQnbGc5sIZC3jMscyv7eP0HgniRx8Dm8jS1rw3lt6+nP4mgTp6Rh455OzCGZ37B4=
  file_glob: true
  file: ./dist/*
  distributions: "sdist bdist_wheel"
  on:
    repo: mpmkp2020/xlrd_demo
